repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: trailing-whitespace # trims trailing whitespace.

      # python specific checks
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.

      # json specific checks
      - id: check-json # checks json files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.3
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
