name: Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          make install

      - name: Run Lint
        run: |
          make lint

      - name: Run Format
        run: |
          make format

      - name: Run Tests
        run: |
          make test
